export const numericFilterKeys = [
   'min_suites',
   'max_suites',
   'min_parking_spaces',
   'max_parking_spaces',
   'min_bedrooms',
   'max_bedrooms',
   'min_bathrooms',
   'max_bathrooms',
   'min_total_area',
   'max_total_area',
   'min_usable_area',
   'max_usable_area',
   'min_rent_price',
   'max_rent_price',
   'min_sale_price',
   'max_sale_price',
   'page',
] as const;

export const propertyTypeOptions = [
   {value: 'Apartamento+', label: 'Apartamento'},
   {value: 'Casa', label: 'Casa'},
   {value: 'Cobertura', label: 'Cobertura'},
   {value: 'Edifício+Comercial', label: 'Comercial'},
   {value: 'Terreno', label: 'Terreno'},
];

export const listingTypesOptions = [
   {label: 'Venda', value: 'sale'},
   {label: 'Locação', value: 'rent'},
];

export const cities = [
   'São Paulo',
   'Rio de Janeiro',
   'Angra dos Reis',
   'Araçariguama',
   'Araçoiaba da Serra',
   'Arandu',
   'Armação dos Búzios',
   'Atibaia',
   'Arujá',
   'Avaré',
   'Barueri',
   'Bertioga',
   'Bragança Paulista',
   'Cabreúva',
   'Campinas',
   'Campos do Jordão',
   'Caraguatatuba',
   'Carapicuíba',
   'Cotia',
   'Coruripe',
   'Diadema',
   'Florianópolis',
   'Guarujá',
   'Guarulhos',
   'Ilha Bela',
   'Indaiatuba',
   'Itapevi',
   'Itapema',
   'Itatiba',
   'Itaí',
   'Itu',
   'Itupeva',
   'Jandira',
   'Jarinu',
   'Jundiaí',
   'Maraú',
   'Mogi das Cruzes',
   'Monte Mor',
   'Orlando',
   'Osasco',
   'Paranapanema',
   'Piracaia',
   'Porto Feliz',
   'Porto Seguro',
   'Prado',
   'Presidente Olegário',
   'Ribeirão Preto',
   'Rio Grande',
   'Salto',
   'Santana de Parnaíba',
   'Santo André',
   'Santos',
   'São Carlos',
   'São Roque',
   'São Sebastião',
   'Sorocaba',
   'Sumaré',
   'Tabatinga',
   'Trancoso',
   'Ubatuba',
   'Votorantim',
];

export const neighborhoods = [
   // Prioritários na ordem especificada:
   'Jardim Europa',
   'Itaim Bibi',
   'Vila Nova Conceição',
   'Jardim Paulistano',
   'Jardim America',
   'Jardim Paulista',
   'Cidade Jardim',
   'Alto Pinheiros',
   'Campo Belo',
   'Vila Olímpia',

   // Restante em ordem alfabética, sem duplicados:
   'Aclimação',
   'Almarias',
   'Alphaville',
   'Alphaville Empresarial',
   'Alphaville Industrial',
   'Alphaville Nova Esplanada',
   'Alphaville Residencial Dois',
   'Alphaville Residencial Um',
   'Alphaville Residencial Zero',
   'Alto',
   'Alto da Boa Vista',
   'Alto da Lapa',
   'Alto do Capivari',
   'Altos de Caucaia Caucaia do Alto',
   'Altos de São Fernando',
   'Baleia São Sebastião',
   'Balneario Praia do Perequê',
   'Balneário Praia do Pernambuco',
   'Barra da Tijuca',
   'Barra Funda',
   'Bela Aliança',
   'Bela Vista',
   'Bertioga Km10,5',
   'Bom Retiro',
   'Bosque da Saúde',
   'Brás',
   'Brooklin',
   'Brooklin Novo',
   'Brooklin Paulista',
   'Caçandoca',
   'Camburi',
   'Cantareira',
   'Casa Verde',
   'Caxingui',
   'Cerqueira César',
   'Chácara Flora',
   'Chácara Monte Alegre',
   'Chácara Polaris',
   'Chácara Santa Lúcia',
   'Chacara Santa Terezinha',
   'Chácara Santo Amaro',
   'Chácara Santo Antônio Zona Sul',
   'Chácaras Reunidas Anhangüera Nova Veneza',
   'Chácaras São Carlos',
   'Cidade Industrial Satélite de São Paulo',
   'Cidade Líder',
   'City América',
   'City Castello',
   'Colinas da Anhangüera',
   'Colinas do Mosteiro de Itaici',
   'Condominio Iporanga',
   'Condomínio da Represa',
   'Condomínio Nova São Paulo',
   'Condomínio Terras de São José',
   'Consolação',
   'Domingas Dias',
   'Ecoville',
   'Eldorado',
   'Engenho Novo',
   'Estancia Velha',
   'Fazenda Boa Vista',
   'Fazenda da Grama',
   'Fazenda Dona Carolina',
   'Fazenda Morumbi',
   'Fazenda Santo Antonio',
   'Fazenda Vila Real de Itu',
   'Feiticeira',
   'Fojo',
   'Freguesia do Ó',
   'Frade Cunhambebe',
   'Fonte Simão',
   'Guaeca',
   'Guaxinduva',
   'Higienópolis',
   'Ilha Bela',
   'Instituto de Previdência',
   'Interlagos',
   'Ipanema',
   'Iporanga',
   'Itapetininga',
   'Itupeva',
   'Ivoturucaia',
   'Jacarepaguá',
   'Jabaquara',
   'Jardim',
   'Jardim Aeroporto',
   'Jardim Ana Estela',
   'Jardim Anália Franco',
   'Jardim Aurélia',
   'Jardim Belvedere',
   'Jardim Botânico',
   'Jardim Campo Grande',
   'Jardim Carolina',
   'Jardim Caravelas',
   'Jardim Claudia',
   'Jardim das Bandeiras',
   'Jardim das Flores',
   'Jardim das Samambaias',
   'Jardim das Vertentes',
   'Jardim do Golf I',
   'Jardim Everest',
   'Jardim Flor do Campo',
   'Jardim Fonte do Morumbi',
   'Jardim Guedala',
   'Jardim Jussara',
   'Jardim Leonor',
   'Jardim Luzitânia',
   'Jardim Marajoara',
   'Jardim Mediterrâneo',
   'Jardim Morumbi',
   'Jardim Mutinga',
   'Jardim Nova São Carlos',
   'Jardim Novo Mundo',
   'Jardim Panorama Zona Sul',
   'Jardim Paraíso',
   'Jardim Petrópolis',
   'Jardim Promissão',
   'Jardim Quintas da Terracota',
   'Jardim Santa Emília',
   'Jardim Santa Helena',
   'Jardim São Luís',
   'Jardim São Miguel',
   'Jardim Sílvia Zona Oeste',
   'Jardim Taquaral',
   'Jardim Tejereba',
   'Jardim Torino',
   'Jardim Universidade Pinheiros',
   'Jardim Vera Cruz',
   'Jardim Vitória Régia',
   'Jardim Vila Mariana',
   'Joá',
   'João Paulo',
   'Liberdade',
   'Lapa',
   'Loteamento Alphaville Campinas',
   'Luz',
   'Mangaratiba',
   'Manancial',
   'Marapé',
   'Marina Canal',
   'Maresias',
   'Meia Praia',
   'Medeiros',
   'Mirandópolis',
   'Moema',
   'Moema Pássaros',
   'Monte Mor',
   'Morro do Carmo',
   'Morro dos Ingleses',
   'Morada da Praia',
   'Morumbi',
   'Nova Higienópolis',
   'Pacaembu',
   'Paquetá',
   'Paineiras do Morumbi',
   'Panamby',
   'Paraíso',
   'Paraíso do Morumbi',
   'Parque Campolim',
   'Parque da Mooca',
   'Parque dos Príncipes',
   'Parque Enseada',
   'Parque Ibirapuera',
   'Parque Novo Mundo',
   'Parque Santa Cecília',
   'Parque Taquaral',
   'Passo Fundo',
   'Pedra do Fogo',
   'Pedregulho',
   'Pera',
   'Pinhal',
   'Pinheiros',
   'Ponta da Baleia',
   'Ponte Firme',
   'Ponte Pequena',
   'Porto Ferreira',
   'Presidente Altino',
   'Quinta da Baroneza',
   'Real Parque',
   'Recanto das Flores',
   'Recanto dos Pássaros',
   'Represa de Jurumirim',
   'Retiro',
   'Retiro Morumbi',
   'Residencial Morada dos Lagos',
   'Residencial Tamboré',
   'Riviera de São Lourenço',
   'Rivieira de São Lourenço',
   'Santa Cecília',
   'Santana',
   'Sítio da Moenda',
   'Sítio dos Britos',
   'Saúde',
   'Shamballa Iii',
   'Socorro',
   'Sumaré',
   'Sumarezinho',
   'Summertime Barreiro',
   'Swiss Park',
   'Tabatinga',
   'Tamboré',
   'Tanquinhos',
   'Tenório',
   'Terras de Santa Rosa',
   'Toque-Toque Grande',
   'Toriba',
   'Tortuga',
   'Trancoso',
   'Tucuruvi',
   'Urubu',
   'Usina',
   'Várzea da Barra Funda',
   'Vila',
   'Vila Almeida',
   'Vila Andrade',
   'Vila Buarque',
   'Vila Caraguatá',
   'Vila Clementino',
   'Vila Congonhas',
   'Vila da Saúde',
   'Vila Emir',
   'Vila Ester Zona Norte',
   'Vila Gea',
   'Vila Ida',
   'Vila Ipojuca',
   'Vila Inah',
   'Vila Inglesa',
   'Vila Leopoldina',
   'Vila Madalena',
   'Vila Mantiqueira',
   'Vila Mariana',
   'Vila Mascote',
   'Vila Monumento',
   'Vila Monte Alegre',
   'Vila Morumbi',
   'Vila Oliveira',
   'Vila Progredior',
   'Vila Real',
   'Vila Ribeiro de Barros',
   'Vila Romana',
   'Vila Santo Antônio',
   'Vila Santo Estéfano',
   'Vila São Miguel',
   'Vila Suzana',
   'Vila Tramontano',
   'Vila Velha',
   'Winter Garden',
];
